export default [
  {
    path: '/user',
    layout: false,
    routes: [{ name: '登录', path: '/user/login', component: './User/Login' }],
  },
  { path: '/welcome', name: '欢迎', icon: 'smile', component: './Welcome' },
  {
    path: '/user/list',
    name: '用户管理',
    icon: 'user',
    component: './User/List',
  },
  {
    path: '/book/list',
    name: '图书管理',
    icon: 'book',
    component: './Book/List',
  },
  {
    path: '/card/list',
    name: '校园卡管理',
    icon: 'CreditCard',
    component: './CampusCard/List',
  },
  {
    path: '/announcement/list',
    name: '公告管理',
    icon: 'Bell',
    component: './Announcement/List',
  },
  {
    path: '/course/list',
    name: '课程管理',
    icon: 'Read',
    component: './Course/List',
  },
  {
    path: '/survey/list',
    name: '问卷管理',
    icon: 'Snippets',
    component: './Survey/List',
  },
  {
    path: '/book',
    name: '图书资源',
    icon: 'Book',
    routes: [
      { path: 'search', name: '图书借阅', component: './Book/Search' },
      { path: 'borrowed', name: '我的借阅', component: './Book/Borrowed' },
    ],
  },
  {
    path: '/card',
    name: '校园卡',
    icon: 'CreditCard',
    routes: [
      { path: 'record', name: '消费记录', component: './CampusCard/Record' },
      { path: 'myCard', name: '我的校园卡', component: './CampusCard/MyCard' },
    ],
  },
  { path: '/', redirect: '/welcome' },
  { path: '*', layout: false, component: './404' },
  { path: '/user/addOrUpdate/:id', component: './User/AddOrUpdate' },
  { path: '/user/addOrUpdate', component: './User/AddOrUpdate' },
  { path: '/book/addOrUpdate/:id', component: './Book/AddOrUpdate' },
  { path: '/book/addOrUpdate', component: './Book/AddOrUpdate' },
  { path: '/announcement/addOrUpdate/:id', component: './Announcement/AddOrUpdate' },
  { path: '/announcement/addOrUpdate', component: './Announcement/AddOrUpdate' },
  { path: '/course/addOrUpdate/:id', component: './Course/AddOrUpdate' },
  { path: '/course/addOrUpdate', component: './Course/AddOrUpdate' },
  { path: '/survey/addOrUpdate/:id', component: './Survey/AddOrUpdate' },
  { path: '/survey/addOrUpdate', component: './Survey/AddOrUpdate' },
  { path: '/survey/fill/:id', component: './Survey/Fill' },
  { path: '/survey/analysis/:id', component: './Survey/Analysis' },
  { path: '/book/detail/:bookId', component: './Book/Detail' },
];
