export default [
  {
    path: '/user',
    layout: false,
    routes: [{ name: '登录', path: '/user/login', component: './User/Login' }],
  },
  { path: '/welcome', name: '欢迎', icon: 'smile', component: './Welcome' },
  {
    path: '/user/list',
    name: '用户管理',
    icon: 'user',
    access: 'isAdmin',
    component: './User/List',
  },
  {
    path: '/book/list',
    name: '图书管理',
    icon: 'book',
    access: 'isAdmin',
    component: './Book/List',
  },
  {
    path: '/card/list',
    name: '校园卡管理',
    icon: 'CreditCard',
    access: 'isAdmin',
    component: './CampusCard/List',
  },
  {
    path: '/announcement/list',
    name: '公告管理',
    icon: 'Bell',
    access: 'isAdmin',
    component: './Announcement/List',
  },
  {
    path: '/course/list',
    name: '课程管理',
    icon: 'Read',
    access: 'isAdmin',
    component: './Course/List',
  },

  {
    path: '/survey/list',
    name: '问卷管理',
    icon: 'Snippets',
    access: 'isAdmin',
    component: './Survey/List',
  },
  {
    path: '/college/list',
    name: '学院管理',
    icon: 'Bank',
    access: 'isAdmin',
    component: './College/List',
  },
  {
    path: '/major/list',
    name: '专业管理',
    access: 'isAdmin',
    icon: 'FundProjectionScreen',
    component: './Major/List',
  },
  {
    path: '/class/list',
    name: '班级管理',
    icon: 'Home',
    access: 'isTeacherOrAdmin',
    component: './Class/List',
  },
  {
    path: '/course/my',
    name: '我的课程',
    icon: 'Read',
    access: 'isTeacher',
    component: './Course/TeacherCourse',
  },
  {
    path: '/course/feedback',
    name: '课程反馈统计',
    icon: 'BarChart',
    access: 'isTeacher',
    component: './Course/Feedback',
  },
  {
    path: '/book',
    name: '图书资源',
    access: 'isTeacherOrStudent',
    icon: 'Book',
    routes: [
      { path: 'search', name: '图书借阅', component: './Book/Search' },
      { path: 'borrowed', name: '我的借阅', component: './Book/Borrowed' },
    ],
  },
  {
    path: '/course',
    name: '我的课程',
    access: 'isStudent',
    icon: 'Read',
    routes: [
      { path: 'select', name: '选课中心', component: './Course/Select' },
      { path: 'mySelected', name: '已选课程', component: './Course/MySelected' },
      { path: 'myCourse', name: '我的课表', component: './Course/MyCourse' },
    ],
  },
  {
    path: '/grade/list',
    name: '我的成绩',
    icon: 'Trophy',
    access: 'isStudent',
    component: './Grade/List',
  },
  {
    path: '/card',
    name: '校园卡',
    icon: 'CreditCard',
    access: 'isTeacherOrStudent',
    routes: [
      { path: 'record', name: '消费记录', component: './CampusCard/Record' },
      { path: 'myCard', name: '我的校园卡', component: './CampusCard/MyCard' },
    ],
  },
  {
    path: '/my',
    name: '个人中心',
    icon: 'User',
    access: 'isTeacherOrStudent',
    routes: [
      { path: 'profile', name: '个人信息', component: './Center/Profile' },
      { path: 'changePassword', name: '修改密码', component: './Center/ChangePassword' },
    ],
  },
  { path: '/', redirect: '/welcome' },
  { path: '*', layout: false, component: './404' },
  { path: '/user/addOrUpdate/:id', component: './User/AddOrUpdate' },
  { path: '/user/addOrUpdate', component: './User/AddOrUpdate' },
  { path: '/book/addOrUpdate/:id', component: './Book/AddOrUpdate' },
  { path: '/book/addOrUpdate', component: './Book/AddOrUpdate' },
  { path: '/announcement/addOrUpdate/:id', component: './Announcement/AddOrUpdate' },
  { path: '/announcement/addOrUpdate', component: './Announcement/AddOrUpdate' },
  { path: '/course/addOrUpdate/:id', component: './Course/AddOrUpdate' },
  { path: '/course/grade/:id', component: './Course/Grade' },
  { path: '/course/addOrUpdate', component: './Course/AddOrUpdate' },
  { path: '/survey/addOrUpdate/:id', component: './Survey/AddOrUpdate' },
  { path: '/survey/addOrUpdate', component: './Survey/AddOrUpdate' },
  { path: '/college/addOrUpdate', component: './College/AddOrUpdate' },
  { path: '/college/addOrUpdate/:id', component: './College/AddOrUpdate' },
  { path: '/major/addOrUpdate', component: './Major/AddOrUpdate' },
  { path: '/major/addOrUpdate/:id', component: './Major/AddOrUpdate' },
  { path: '/class/addOrUpdate', component: './Class/AddOrUpdate' },
  { path: '/class/addOrUpdate/:id', component: './Class/AddOrUpdate' },
  { path: '/class/student/:id', component: './Class/Student' },
  { path: '/class/studentAddOrUpdate/:id', component: './Class/StudentAddOrUpdate' },
  { path: '/survey/fill/:id', component: './Survey/Fill' },
  { path: '/survey/analysis/:id', component: './Survey/Analysis' },
  { path: '/book/detail/:bookId', component: './Book/Detail' },
];
