export default [
  {
    path: '/user',
    layout: false,
    routes: [{ name: '登录', path: '/user/login', component: './User/Login' }],
  },
  { path: '/welcome', name: '欢迎', icon: 'smile', component: './Welcome' },
  {
    path: '/user/list',
    name: '用户管理',
    icon: 'user',
    component: './User/List',
  },
  {
    path: '/book/list',
    name: '图书管理',
    icon: 'book',
    component: './Book/List',
  },
  {
    path: '/card/list',
    name: '校园卡管理',
    icon: 'CreditCard',
    component: './CampusCard/List',
  },
  {
    path: '/announcement/list',
    name: '公告管理',
    icon: 'Bell',
    component: './Announcement/List',
  },
  { path: '/', redirect: '/welcome' },
  { path: '*', layout: false, component: './404' },
  { path: '/user/addOrUpdate/:id', component: './User/AddOrUpdate' },
  { path: '/user/addOrUpdate', component: './User/AddOrUpdate' },
  { path: '/book/addOrUpdate/:id', component: './Book/AddOrUpdate' },
  { path: '/book/addOrUpdate', component: './Book/AddOrUpdate' },
  { path: '/announcement/addOrUpdate/:id', component: './Announcement/AddOrUpdate' },
  { path: '/announcement/addOrUpdate', component: './Announcement/AddOrUpdate' },
];
